# Generated by Django 3.1.7 on 2021-04-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_profile',
            field=models.TextField(null=True),
        ),
    ]
