# Generated by Django 3.1.7 on 2021-03-31 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=255)),
                ('total_target', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=255)),
                ('start_date', models.DateField(max_length=255)),
                ('end_date', models.DateField(max_length=255)),
                ('donations', models.ManyToManyField(related_name='user_donation', through='home.Donation', to='home.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Project',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.project')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
        migrations.CreateModel(
            name='Rate_Project',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.project')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.users')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Tags',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Pictures',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='rates',
            field=models.ManyToManyField(related_name='user_rate', through='home.Rate_Project', to='home.Users'),
        ),
        migrations.AddField(
            model_name='project',
            name='reports',
            field=models.ManyToManyField(related_name='user_report', through='home.Report_Project', to='home.Users'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='home.users'),
        ),
        migrations.AddField(
            model_name='donation',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.project'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.users'),
        ),
    ]
