# Generated by Django 3.1.7 on 2021-03-31 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210331_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('time', models.DateField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Comment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='home.comment')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='home.users')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='reports',
            field=models.ManyToManyField(related_name='user_comment_report', through='home.Report_Comment', to='home.Users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='home.users'),
        ),
    ]
