# Generated by Django 3.1.7 on 2021-04-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210401_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/images'),
        ),
    ]
