# Generated by Django 3.1.7 on 2021-04-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_users_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_pictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/users'),
        ),
    ]
