# Generated by Django 3.1.7 on 2021-04-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210402_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_pictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
