# Generated by Django 3.1.7 on 2021-04-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210402_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
