# Generated by Django 3.1.7 on 2021-04-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210406_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_pictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Image'),
        ),
    ]
