# Generated by Django 3.1.7 on 2021-04-09 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210408_2139'),
        ('home', '0010_auto_20210404_0037'),
    ]

    operations = [
    ]
