# Generated by Django 3.1.7 on 2021-04-09 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210409_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_project',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
