# Generated by Django 3.1.7 on 2021-04-10 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210410_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_project',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
