# Generated by Django 3.1.7 on 2021-04-10 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210410_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_project',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
