# Generated by Django 3.1.7 on 2021-04-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210410_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate_project',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
