# Generated by Django 3.1.7 on 2021-04-10 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210410_0255'),
        ('home', '0017_merge_20210410_0107'),
    ]

    operations = [
    ]
