# Generated by Django 3.1.7 on 2021-04-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_merge_20210410_0410'),
        ('home', '0018_auto_20210410_0250'),
    ]

    operations = [
    ]
