# Generated by Django 3.1.7 on 2021-04-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_merge_20210411_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_pictures',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.project'),
        ),
    ]
