# Generated by Django 3.1.7 on 2021-04-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210410_2317'),
        ('home', '0026_auto_20210411_0323'),
    ]

    operations = [
    ]
