# Generated by Django 3.1.7 on 2021-04-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_merge_20210411_0332'),
        ('home', '0027_merge_20210411_0214'),
    ]

    operations = [
    ]
